#ifndef BTSTACK_CONFIG_H
#define BTSTACK_CONFIG_H
#define ENABLE_BLE
#define ENABLE_LE_PERIPHERAL
#define ENABLE_LE_SECURE_CONNECTIONS
#define ENABLE_LE_DATA_LENGTH_EXTENSION
#define HCI_ACL_PAYLOAD_SIZE (255+4)
#define MAX_NR_GATT_CLIENTS 1
#define MAX_NR_HCI_CONNECTIONS 1
#define MAX_NR_SM_LOOKUP_ENTRIES 3
#define MAX_NR_WHITELIST_ENTRIES 4
#define MAX_NR_LE_DEVICE_DB_ENTRIES 8      // bonded hosts; we use 4 slots
#define NVM_NUM_DEVICE_DB_ENTRIES 8        // bonds persist in flash
#define HAVE_EMBEDDED_TIME_MS
#define HAVE_MALLOC
#define HCI_OUTGOING_PRE_BUFFER_SIZE 4
#define HCI_HOST_ACL_PACKET_NUM 4
#endif
